#!/usr/bin/perl
use File::Next;

my $templatefile = <<'END_TEMPLATE';
<html><body bgcolor="#FFFFFF"></body></html>
END_TEMPLATE
my $file = "";
my $DEBUG_MODE = "off";

sub PrintDebugCommand
{
        if ($DEBUG_MODE eq "off")
        {
                return;
        }
        my $PassedString = shift;
        print "$PassedString\n";
	#print "Press Enter To Run This:";
	#my $entered = <STDIN>;
}

sub CreateIndex
{
	my $OutputFile = "$file/index.html";
	if (-f $OutputFile)
	{
		print "$OutputFile already exists - skipping\n";
		next;
	}
	open(FH, '>', $OutputFile) or die $!;
	print FH "$templatefile";
	close(FH);
}
my $iter = File::Next::dirs( '.' );
while ( defined ( $file = $iter->() ) )
{
	if (substr($file, 0, 1) eq ".")
	{
		next;
	}
	if (index($file, ".git") != -1)
	{
		PrintDebugCommand("$file contains .git");
		next;
	}
	PrintDebugCommand("saw $file");
	CreateIndex();
}

exit 0;
